version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test: 
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests and Builds
          command: |
            npm test
            npm start
          
      - persist_to_workspace:
          root: ~/project
          paths:
            - .