version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build: 
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests and Builds
          command: |
            npm test
          
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor: node/default
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ""
      - run:
          name: Make remote server a known host
          command: ssh-keyscan oncesync.duckdns.org >> ~/.ssh/known_hosts
      - run:
          name: Execute Ansible
          command: |
            pip install ansible
            ansible-playbook -i hosts playbook.yml
workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
